FROM php:7.2.2-apache


RUN apt-get update \
  && apt-get install --yes --no-install-recommends libpq-dev libpng-dev libfreetype6-dev libjpeg62-turbo-dev
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
RUN docker-php-ext-install pdo_pgsql pdo_mysql mbstring exif gd