version: '3'
services:
  web:
    "build":
      "context": "./"
      "dockerfile": "Dockerfile-apache"
    container_name: php_web
    depends_on:
      - bdd
    volumes:
      - .:/var/www/html/
    ports:
      - "80:80"
    stdin_open: true
    tty: true